# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/package/get_package_list/ID/eq/9787111186823
Accept: application/json

###

POST http://127.0.0.1:8080/domain/newTransPackage/11
Content-Type: application/json

{
  "id": "1111113334",
  "sourceNode": "410101",
  "targetNode": "410101",
  "status": 2
}
###

POST http://localhost:8080/domain/createExpressSheet
Content-Type: application/json

{
  "id": "1212221",
  "type": "1",
  "senderId": "1",
  "receverId": "2"
}

###


POST http://localhost:8080/domain/getExpressList
Content-Type: application/json

{
  "recever": "1",
  "accepter": "12"
}

###