# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:8080/expressTrackingSystem_war_exploded/user/addUserInfo
Content-Type: application/json

{
  "pwd": "12345",
  "name": "李伟",
  "urull": "0",
  "telCode": "12345678934",
  "status": "0",
  "dptId": "sdfdsfdsf"
}

###

POST http://localhost:8080/user/doLogin
Content-Type: application/json

{
  "id": "13833554433",
  "password": "aaaa"
}

###
POST  http://localhost:8080/user/login
Content-Type: application/json

{
  "phone": "13833554433",
  "password": "aaaa"
}

###

GET http://localhost:8080/customer/list
Content-Type: application/json

###